# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: randomization.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rsoccer_gym.Simulators.pb_fira.common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='randomization.proto',
  package='fira_message.sim_to_ref',
  syntax='proto3',
  serialized_pb=_b('\n\x13randomization.proto\x12\x17\x66ira_message.sim_to_ref\x1a\x0c\x63ommon.proto\"w\n\rRandomization\x12\x0e\n\x06torque\x18\x01 \x01(\x01\x12\x10\n\x08\x66riction\x18\x02 \x01(\x01\x12\x14\n\x0cvisionNoiseX\x18\x03 \x01(\x01\x12\x14\n\x0cvisionNoiseY\x18\x04 \x01(\x01\x12\x18\n\x10visionNoiseTheta\x18\x05 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RANDOMIZATION = _descriptor.Descriptor(
  name='Randomization',
  full_name='fira_message.sim_to_ref.Randomization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='torque', full_name='fira_message.sim_to_ref.Randomization.torque', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friction', full_name='fira_message.sim_to_ref.Randomization.friction', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visionNoiseX', full_name='fira_message.sim_to_ref.Randomization.visionNoiseX', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visionNoiseY', full_name='fira_message.sim_to_ref.Randomization.visionNoiseY', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visionNoiseTheta', full_name='fira_message.sim_to_ref.Randomization.visionNoiseTheta', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['Randomization'] = _RANDOMIZATION

Randomization = _reflection.GeneratedProtocolMessageType('Randomization', (_message.Message,), dict(
  DESCRIPTOR = _RANDOMIZATION,
  __module__ = 'randomization_pb2'
  # @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Randomization)
  ))
_sym_db.RegisterMessage(Randomization)


# @@protoc_insertion_point(module_scope)
